### ISSUE TITLE
Making "WHY TO JOIN" section responsive for 601 X 1080 to 990 X 1080 screens.

### ISSUE THREAD

**Issue by DeveloperAshish8** [DeveloperAshish8/CodeChamp-s-Website#21]
Please attach an image or video in the PR if your are assigned for this issue.

**Comment by BinniesLite** [comment]
Hi, I would like to work on this issue

**Comment by Aman-0604** [comment]
I would like to this. @DeveloperAshish8 can you assign it to me.

**Comment by DeveloperAshish8** [comment]
Sure @Aman-0604 , I will be assigning you this issue on 30th Sep till than explore the project more.

**Comment by Aman-0604** [comment]
Sure💫

**Comment by Janhvi52** [comment]
![Screenshot (42)](https://user-images.githubusercontent.com/97719669/193176721-48249e46-487a-4269-bce8-339be7856813.png)

@DeveloperAshish8 
I would like to make the "why join us" section responsive for all screens as well as i'll make it more appealing too
please assign me the same since i've handled such issues smoothly in the past,help me making my first pr thankyou!

**Comment by Aman-0604** [comment]
@Janhvi52 I have completed this task successfully and will open a pull request tomorrow. 
You can look at other issues.

**Comment by Janhvi52** [comment]
No problem, Thanks!

**Comment by Janhvi52** [comment]
No problem @Aman-0604  Thanks!

**Comment by Aman-0604** [comment]
@DeveloperAshish8  I have opened a pull request for the same.

**Comment by DeveloperAshish8** [comment]
Sure merging soon

**Comment by DeveloperAshish8** [comment]
Closed with PR #48
